//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppNumberToWords.Tests.ServiceReferenceUnitTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUnitTest.IServiceNumberToWords")]
    public interface IServiceNumberToWords {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNumberToWords/GetName", ReplyAction="http://tempuri.org/IServiceNumberToWords/GetNameResponse")]
        string GetName(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNumberToWords/GetName", ReplyAction="http://tempuri.org/IServiceNumberToWords/GetNameResponse")]
        System.Threading.Tasks.Task<string> GetNameAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNumberToWords/ConvertNumbertoWord", ReplyAction="http://tempuri.org/IServiceNumberToWords/ConvertNumbertoWordResponse")]
        string ConvertNumbertoWord(string Number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNumberToWords/ConvertNumbertoWord", ReplyAction="http://tempuri.org/IServiceNumberToWords/ConvertNumbertoWordResponse")]
        System.Threading.Tasks.Task<string> ConvertNumbertoWordAsync(string Number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceNumberToWordsChannel : WebAppNumberToWords.Tests.ServiceReferenceUnitTest.IServiceNumberToWords, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNumberToWordsClient : System.ServiceModel.ClientBase<WebAppNumberToWords.Tests.ServiceReferenceUnitTest.IServiceNumberToWords>, WebAppNumberToWords.Tests.ServiceReferenceUnitTest.IServiceNumberToWords {
        
        public ServiceNumberToWordsClient() {
        }
        
        public ServiceNumberToWordsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNumberToWordsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNumberToWordsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNumberToWordsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetName(string Name) {
            return base.Channel.GetName(Name);
        }
        
        public System.Threading.Tasks.Task<string> GetNameAsync(string Name) {
            return base.Channel.GetNameAsync(Name);
        }
        
        public string ConvertNumbertoWord(string Number) {
            return base.Channel.ConvertNumbertoWord(Number);
        }
        
        public System.Threading.Tasks.Task<string> ConvertNumbertoWordAsync(string Number) {
            return base.Channel.ConvertNumbertoWordAsync(Number);
        }
    }
}
